sudo: required
dist: trusty
language: node_js

git:
  depth: 3

cache:
  directories:
    - node_modules

node_js:
- '6.4'

before_script:
 #todo: Figure out a way to use yarn to speed up package installs
  - npm run build

script: npm test
